### ISSUE TITLE
Question about conversation and feature limitations in Tiledesk installation

### ISSUE THREAD

**Issue by beginner1393** [Tiledesk/tiledesk#35]
Hi Tiledesk Team,

I’ve installed your project using the docker-compose.yml file, and everything is working smoothly. However, I noticed some limitations, such as a cap of 200 conversations and restrictions on certain features.

I’d like to ask:

Are these limitations related to the free/open-source version or my installation settings?
Is it possible to remove these limitations in the open-source version?
If activation of a license or configuration changes are required, could you please provide guidance?
Thank you in advance for your assistance!

**Comment by CKaranD** [comment]
hi @beginner1393 !

i am getting this error: at processTimers (node:internal/timers:502:7)] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkTimeoutError: connection timed out\n    at connectionFailureError (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:362:14)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:330:16)\n    at Object.onceWrapper (node:events:627:28)\n    at Socket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:550:8)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)]\n    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:441:11)\n    at Pool.emit (node:events:513:28)\n    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:564:14\n    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:1000:11\n    at /usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:300:5)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:330:7)\n    at Object.onceWrapper (node:events:627:28)\n    at Socket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:550:8)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)"}

did you face similar issue last time?
